# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the bild comnd an `artifact-name` to assign a name to
# distinguish build outputs from each other
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_let", "corne_right" ]
# include:
#   - board: dn9_rev
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCOFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right
  - board: nice_nano_v2
    shield: lily58_dongle
  - board: nice_nano_v2
    shield: settings_reset
